# Generated by Django 6.0.2 on 2026-02-20 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WaterMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rg_code', models.CharField(max_length=10)),
                ('internal_number', models.IntegerField()),
                ('serial_id', models.CharField(max_length=15)),
                ('subscriber_name', models.CharField(max_length=200)),
                ('raw_address', models.CharField(max_length=200)),
            ],
        ),
    ]
