# Generated by Django 6.0.3 on 2026-03-14 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('value_m3', models.PositiveBigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('water_meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='infrastructures.watermeter')),
            ],
        ),
    ]
