# Generated by Django 6.0.3 on 2026-03-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('infrastructures', '0002_reading'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('street_number', models.CharField(blank=True, max_length=20)),
                ('street_name', models.CharField(blank=True, max_length=150)),
                (
                    'address_complement',
                    models.CharField(blank=True, max_length=150),
                ),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': [
                    'city',
                    'postal_code',
                    'street_name',
                    'street_number',
                ],
            },
        ),
        migrations.AddField(
            model_name='watermeter',
            name='address',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='water_meters',
                to='infrastructures.address',
            ),
        ),
    ]
